### ISSUE TITLE
Remove `rowid` column in the SQLite database?

### ISSUE THREAD

**Issue by fmichonneau** [weecology/portal-teachingdb#1]
All the tables have a `rowid` column. At a recent workshop, some participants were confused that there were two columns with the same information (record_id and rowid in the surveys table for instance). Should it be removed? I don't recall these columns being present in earlier versions of the data base.

**Comment by ethanwhite** [comment]
The `rowid` is actually something from SQLite. It's not an actual column in the database per se. You can see this using `SELECT * FROM ...` which won't display `rowid`.
