### ISSUE TITLE
portal_mammals.sqlite has incorrect column types

### ISSUE THREAD

**Issue by remram44** [weecology/portal-teachingdb#3]
The `surveys.hindfoot_length` and `surveys.weight` fields are INTEGER but should be REAL. This can cause issue when doing operations such as `weight/1000` (gives out `0` instead of `0.042`). Note that the types are already correct in the JSON files (`"hindfoot_length":35.0,"weight":40.0`).

cc datacarpentry/sql-ecology-lesson#202

**Comment by ethanwhite** [comment]
Fixed in #5 (merged in locally). Thanks @remram44!
