### ISSUE TITLE
More context on the disclaimer?

### ISSUE THREAD

**Issue by cboettig** [weecology/portal-teachingdb#8]
The README notes:

> This database is not designed for research as it intentionally removes some of the real-world complexities

I'm all for researchers using the original sources from Ecological archives, but I was just curious if this was referring to a particular assumption in the cleaning that would be problematic?  Maybe it's just my novice python, but if someone just showed me the script at https://github.com/weecology/portal-teachingdb/blob/master/create_portal_teaching_dataset.py and asked me if it included any step that might be okay for classroom use but potentially problematic for research purposes I'm not sure what would jump out at me.  Is there a particular dubious line?  (e.g. maybe certain values being re-coded as `NA` for simplicity?)  

(I guess I always find statements like this intriguing because I suspect research is full of these simplifications anyway but it often hard to pinpoint specific examples and the consequences to inference, if any).

**Comment by ethanwhite** [comment]
Good point (as usual) @cboettig. What do you think about #9?
